name: mosaic_doctors
description: MOSAIC doctors app
publish_to: 'none'
version: 4.0.1+401

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  get: ^4.3.8
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  jiffy: ^4.1.0
  flutter_keyboard_visibility: ^5.0.2
  printing: ^5.2.1
  flutter_local_notifications: ^9.0.2
  rxdart: ^0.23.1
  linked_scroll_controller: ^0.1.2
  firebase_messaging:  ^10.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  loading_overlay: ^0.3.0
  pdf: ^3.5.0
  shared_preferences: ^2.0.6
  encrypt: ^5.0.0
  cupertino_icons: ^1.0.0
  get_it: 7.2.0
  flutter_screenutil: ^5.0.0+2
  path_provider: ^2.0.2
  open_file: ^3.0.3
  device_info: ^2.0.2
  permission_handler: ^8.2.6
  marquee: ^2.2.0
  reviews_slider: ^2.0.0
  date_time_picker: ^2.1.0
  checkbox_grouped: ^1.7.0
  file_picker: ^3.0.1
  country_picker: ^2.0.8
  country_currency_pickers: 2.0.0
  dio: ^4.0.1
  path: ^1.6.4
  sticky_headers: "^0.1.8"
  smart_select: ^4.3.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

 # flutter_launcher_icons: "^0.9.0"
 # mation on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/encryptionKeys/

  fonts:
    - family: droid
      fonts:
        - asset: assets/fonts/DroidKufi-Regular.ttf
    - family: karbon
      fonts:
        - asset: assets/fonts/DroidKufi-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
